# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccf44f1ef66dde01b025195d3eefb253abc9d582b2067304e8e5d254f4cf4b7d634f66de7ca200165e4480f4ddd48aea9cb9ca1be8e1c58bd04dd008170bbfa1

test:
  secret_key_base: 0e272f89872545429a56c69aba31882b9c9af97d744a50b2dcd78241f34924828c7e782676c68ce39939dc3675f06ce3cb578b915c265a5a636f7836b211c6e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
